//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SevvalImre_Proje.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kampanya
    {
        public int KampanyaID { get; set; }
        public string KampanyaAd { get; set; }
        public System.DateTime KampanyaTarihleri { get; set; }
        public int RestoranID { get; set; }
    
        public virtual Restoran Restoran { get; set; }
    }
}
