//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SevvalImre_Proje.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Masa
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Masa()
        {
            this.Rezervasyonlar = new HashSet<Rezervasyonlar>();
        }
    
        public int MasaID { get; set; }
        public string MasaNo { get; set; }
        public string Konum { get; set; }
        public string SandelyeSayisi { get; set; }
        public int RestoranID { get; set; }
    
        public virtual Restoran Restoran { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Rezervasyonlar> Rezervasyonlar { get; set; }
    }
}
