//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SevvalImre_Proje.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class RestoranRezervasyonEntities : DbContext
    {
        public RestoranRezervasyonEntities()
            : base("name=RestoranRezervasyonEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Ilceler> Ilceler { get; set; }
        public virtual DbSet<Iller> Iller { get; set; }
        public virtual DbSet<Kampanya> Kampanya { get; set; }
        public virtual DbSet<Kategori> Kategori { get; set; }
        public virtual DbSet<Restoran> Restoran { get; set; }
        public virtual DbSet<Sube> Sube { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Kampanyali_Restoranlar> Kampanyali_Restoranlar { get; set; }
        public virtual DbSet<Kategorilerine_Gore_Restoran_Listesi> Kategorilerine_Gore_Restoran_Listesi { get; set; }
        public virtual DbSet<Sehirlere_Gore_Restoranlar> Sehirlere_Gore_Restoranlar { get; set; }
        public virtual DbSet<Illerin_ilceleri> Illerin_ilceleri { get; set; }
        public virtual DbSet<Kulllanici_Listele> Kulllanici_Listele { get; set; }
        public virtual DbSet<Masa> Masa { get; set; }
        public virtual DbSet<Kullanici> Kullanici { get; set; }
        public virtual DbSet<KullaniciRol> KullaniciRol { get; set; }
        public virtual DbSet<Roller> Roller { get; set; }
        public virtual DbSet<Sikayet> Sikayet { get; set; }
        public virtual DbSet<Rezervasyonlar> Rezervasyonlar { get; set; }
    
        public virtual ObjectResult<Kullanicilar_Tipleri_Result> Kullanicilar_Tipleri()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Kullanicilar_Tipleri_Result>("Kullanicilar_Tipleri");
        }
    
        public virtual ObjectResult<Kulllanici_Rolleri_Result> Kulllanici_Rolleri()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Kulllanici_Rolleri_Result>("Kulllanici_Rolleri");
        }
    
        public virtual ObjectResult<string> MasaKonumu()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("MasaKonumu");
        }
    
        public virtual ObjectResult<Nullable<int>> MasaNumarası()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("MasaNumarası");
        }
    }
}
