//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SevvalImre_Proje.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rezervasyonlar
    {
        public int RezervasyonID { get; set; }
        public System.DateTime RezervasyonTarihi { get; set; }
        public int MasaID { get; set; }
        public int RestoranID { get; set; }
        public string MusteriAd { get; set; }
        public string MusteriSoyad { get; set; }
        public Nullable<int> KullaniciID { get; set; }
    
        public virtual Kullanici Kullanici { get; set; }
        public virtual Masa Masa { get; set; }
        public virtual Restoran Restoran { get; set; }
    }
}
