//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SevvalImre_Proje.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Roller
    {
        public int ID { get; set; }
        public int KullaniciID { get; set; }
        public int RolID { get; set; }
    
        public virtual Kullanici Kullanici { get; set; }
        public virtual KullaniciRol KullaniciRol { get; set; }
    }
}
