//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SevvalImre_Proje.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sehirlere_Gore_Restoranlar
    {
        public string RestoranAd { get; set; }
        public string IlAd { get; set; }
        public string IlceAd { get; set; }
    }
}
