//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SevvalImre_Proje.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sikayet
    {
        public int SikayetID { get; set; }
        public System.DateTime SikayetTarihi { get; set; }
        public string SikayetNedeni { get; set; }
        public int KullaniciID { get; set; }
        public string MusteriAd { get; set; }
        public string MusteriSoyad { get; set; }
        public Nullable<int> RestoranID { get; set; }
    
        public virtual Kullanici Kullanici { get; set; }
        public virtual Restoran Restoran { get; set; }
    }
}
