//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SevvalImre_Proje.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sube
    {
        public int SubeID { get; set; }
        public int RestoranID { get; set; }
        public int IlID { get; set; }
        public int IlceID { get; set; }
    
        public virtual Ilceler Ilceler { get; set; }
        public virtual Iller Iller { get; set; }
        public virtual Restoran Restoran { get; set; }
    }
}
